// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWOoH8rTQM7ANy5-NDIsM__EjtK7CqVlw',
    appId: '1:604293503124:web:2c6a3184497773593f7c81',
    messagingSenderId: '604293503124',
    projectId: 'easacc-task-66430',
    authDomain: 'easacc-task-66430.firebaseapp.com',
    storageBucket: 'easacc-task-66430.firebasestorage.app',
    measurementId: 'G-MH0KGTYSFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMh4iOGtJcdcl3j0R9S40J8rtQJRfHNHQ',
    appId: '1:604293503124:android:96556ac8e88965863f7c81',
    messagingSenderId: '604293503124',
    projectId: 'easacc-task-66430',
    storageBucket: 'easacc-task-66430.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgYfkT8VI0q6ZiPQmcESN1lH5UJ90V2VM',
    appId: '1:604293503124:ios:a2d47b54d7656a353f7c81',
    messagingSenderId: '604293503124',
    projectId: 'easacc-task-66430',
    storageBucket: 'easacc-task-66430.firebasestorage.app',
    iosClientId: '604293503124-dign73fc6cgps3tbdhk3ceep2i2svi91.apps.googleusercontent.com',
    iosBundleId: 'com.example.esaccFlutterTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgYfkT8VI0q6ZiPQmcESN1lH5UJ90V2VM',
    appId: '1:604293503124:ios:a2d47b54d7656a353f7c81',
    messagingSenderId: '604293503124',
    projectId: 'easacc-task-66430',
    storageBucket: 'easacc-task-66430.firebasestorage.app',
    iosClientId: '604293503124-dign73fc6cgps3tbdhk3ceep2i2svi91.apps.googleusercontent.com',
    iosBundleId: 'com.example.esaccFlutterTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWOoH8rTQM7ANy5-NDIsM__EjtK7CqVlw',
    appId: '1:604293503124:web:009f3dfd1964a9b13f7c81',
    messagingSenderId: '604293503124',
    projectId: 'easacc-task-66430',
    authDomain: 'easacc-task-66430.firebaseapp.com',
    storageBucket: 'easacc-task-66430.firebasestorage.app',
    measurementId: 'G-4SERWG0J7Z',
  );
}
